@extends('website.layouts.header')
@section('styles') 
@endsection
@section('content')    
     <!-- Banner Start -->
    <section class="breadcrum-banner d-flex justify-content-center align-items-center">
        <div class="text-center">
            <h1 class="text-white fw-700 exo">Terms & Condition</h1>
        </div>
    </section>
    <!-- Banner End -->
    <!-- Content Section Start -->
    <section class="py-5">
        <div class="container">
            <div class="content-wrap bg-gray p-2 py-5 p-sm-5">
                <h4 class="text-main roboto mb-4 fw-700">1. Acceptance of Terms</h4>
                <p class="roboto f-22 text-white mb-4">
                    Welcome to Zentia (“Service” or “Site”) owned and operated by Zentia Inc (“”).
                </p>
                <p class="roboto f-22 text-white mb-5">
                   By applying to become an Advisor on the Site, you are agreeing to comply with and be bound by the terms of this Advisor Agreement (the “Agreement”), the privacy policy, Advisor community guidelines, and all rules, policies and disclaimers posted on the Site or about which you are notified (collectively “Terms”). Please review all of the Terms carefully before applying to become an Advisor on the Site.
                </p>
                <p class="roboto f-22 text-light mb-5">By using the Site, you:</p>
                <ul class="px-5">
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Agree to be bound by the Terms;</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Represent that you are over the age of eighteen (18) and able to form legally binding contracts;</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Agree and acknowledge that by using the Service you are accepting a benefit that cannot be disgorged;</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Acknowledge that the Service is subject to <a href="https://home.treasury.gov/policy-issues/financial-sanctions/sanctions-programs-and-country-information" class="text-main"> U.S. export controls</a> and agree that you will comply with U.S. export controls; and</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Represent that you are neither located in a <a href="https://home.treasury.gov/policy-issues/office-of-foreign-assets-control-sanctions-programs-and-information" class="text-main">sanctioned country</a>nor a prohibited person.</li>
                </ul>
                <h4 class="text-main roboto mb-4 fw-700">2. Definitions</h4>
                <p class="roboto f-22 text-white mb-5">
                   The words “User,” “you” and “your” refer to the individual or entity that creates an Zentia account. “Zentia,” “we,” “us” and “our” refer to Zentia. “Customer” refers to the person who asks a question on the Site. “Advisor” refers to the person who answers a question on the Site. 
                </p>
                <h4 class="text-main roboto mb-4 fw-700">3. Electronic Communications and Right to Modify Terms</h4>
                <p class="roboto f-22 text-white mb-3">
                  When you visit Zentia or send us e-mails, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail or by posting notices on the Site. You agree that all agreements, 
                </p>
                <p class="roboto f-22 text-white mb-3">
                  notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. You agree to provide us with, and maintain in your Zentia account profile, your current and active email address.
                </p>
                <p class="roboto f-22 text-white mb-3">
                  Zentia reserves the right to change, revise or modify the Terms (including, but not limited to, fees) at any time by posting the amended terms on the Site. All amended terms shall automatically be effective upon posting; provided, however, that those changes that Zentia, in its sole discretion, deems material changes to the Terms will be effective upon the earlier of:
                </p>
                <ul class="px-5">
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">The agreement of the User; or </li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Thirty (30) days after notice to the existing User via an email from an @Zentia.io email address to the User’s email address on file with Zentia or via other means including, but not limited to, a banner, message, or other conspicuous notice on the Zentia website. Your continued use of the Service will signify your acceptance of the changes regardless of whether you actually saw or read the notice regarding such change(s). If you do not accept the changes, your sole and exclusive remedy is to discontinue using Zentia. <br><strong>The latest Terms will be posted on the Site, and you should review them prior to using the Site.</strong></li>
               </ul>
               <h4 class="text-main roboto mb-4 fw-700">4. The Website</h4>
                <p class="roboto f-22 text-white mb-3">
                  The Zentia Site is an online platform for informational and educational purposes, owned and operated by Zentia, that exists solely to broker relationships between Advisors and potential Customers of those Advisors who are interested in purchasing their Advisor services. Zentia is not in the business of providing or selling information or education that is within any Advisor’s area of expertise. Users of the Site, not Zentia, provide the content in Posts (defined below). The Advisors determine, in their sole discretion, which calls to answer and engage. Advisors are not employees or agents of Zentia. Rather, they are independent service providers using the Site to sell their knowledge to Customers and, as such, are along with Customers simply Users of the Site.
                </p>
                <p class="roboto f-22 text-white mb-3">
                  Zentia is not involved in the conversations between Advisors and Customers. Zentia shall not be liable for any acts or omissions of Advisors, content in Posts or calls, the ability of Advisors to answer questions, or the ability of Customers to pay for answers. We cannot ensure that a Customer will complete a transaction. Notwithstanding the foregoing, Zentia reserves the right, but is not obligated, to refuse to post or to remove any content on the Site.
                </p>
                <p class="roboto f-22 text-white mb-3">
                  EMERGENCY QUESTIONS AND CRISIS SITUATIONS (particularly regarding medical or mental health issues) should not be directed to the Site and should, instead be directed immediately by telephone or in-person to qualified professionals (e.g., in the U.S., call 911). The Site is not the appropriate venue to deal with such situations.
                </p>
                 <h4 class="text-main roboto mb-4 fw-700">6. Advisor Representations and Covenants</h4>
                 <p class="roboto f-22 text-white mb-5">By agreeing to this Advisor Agreement and completing the online registration process, you are representing and agreeing that:</p>
                 <p class="roboto f-22 text-white mb-3">(a) All information you provide in your registration with Zentia relates to yourself only and is accurate, complete, and not misleading.</p>
                 <p class="roboto f-22 text-white mb-3">(b) You accurately describe your background, skills, knowledge, and your level of experience (including professional licenses, certifications, education, employment, etc.).</p>
                 <p class="roboto f-22 text-white mb-3">(c) You will not misrepresent yourself, such as, but not limited to, using or creating a misleading username.</p>
                 <p class="roboto f-22 text-white mb-3">(d)</p>
                 <ul class="px-4">
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">You will maintain and update the information described in subsections (a) – (d) above within twenty-four (24) hours of any changes so that it remains true, accurate, and complete. In addition, if any change to such information alters the status of any of your credentials that have been verified for purposes of being an Advisor on the Site (e.g., active license becomes inactive or suspended, disciplinary investigation is opened, etc.), you will notify Zentia of such change by sending an email to Advisors@Zentia.io within twenty-four (24) hours of the change. In addition, if such change makes you ineligible to be an Advisor on the Site, then you must immediately cease answering questions on the Site.</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Zentia reserves the right, and Advisor agrees to comply, to periodically audit the credentials of any Advisor on the platform.</li>
                 </ul>
                 <p class="roboto f-22 text-white mb-3">(e) You will not answer questions in any of the other categories or subcategories if you do not meet the requirements of those categories or subcategories. As an example, you will not answer questions in any of the Legal, Medical or Veterinary categories or subcategories unless you are a licensed attorney, MD/DO or veterinarian (or the local equivalent), respectively, with an active license in good standing. If you are unclear about the requirements for Advisors in particular categories or subcategories, please email Advisors@Zentia.io. </p>
                 <p class="roboto f-22 text-white mb-3">(f) You will provide competent answers that are within your realm of expertise and any applicable credentials only, and will use at least a reasonable standard of care in providing answers. A reasonable standard of care is the higher of:  </p>
                 <ul class="px-4">
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">(i) the standard you apply in your profession not conducted on the Site; or </li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">(ii) the standard of care required by the applicable profession.</li>
                 </ul>
                 <p class="roboto f-22 text-white mb-3">(g) Advisors in the Medical, Health, Veterinary, Pet, or Large Animal categories shall provide general information only, not medical or veterinary advice.   They shall not diagnose, treat, or recommend treatment or a course of action that should only be performed or recommended after an in-person examination or meeting, and they shall not act in a manner or engage in a form of communication that would establish a professional-client relationship on the Site; however, they may do so outside of the Site.</p>
                 <p class="roboto f-22 text-white mb-3">(h) Advisors in the Legal categories must be attorneys licensed to practice law, and be in good standing, in at least one jurisdiction in the United States or foreign country. Such Advisors shall provide general information only, such as providing descriptions of general principles of law, and shall not provide legal advice. In responding to questions, Advisors in the Legal Category shall not apply their legal knowledge or skills to resolve or advise on the Customer’s specific factual circumstances described in the question, such as by proposing a specific course of action (other than advising the User to seek the advice of an attorney licensed to practice in the relevant jurisdiction). Advisors in the Legal Category shall not form an attorney-client relationship on the Site; however, they may do so outside of the Site.</p>
                 <p class="roboto f-22 text-white mb-3">(i) You will not do anything to manipulate, undermine, or disrupt the integrity of any Customer, Advisor, or other feedback ratings, reports, or systems on the Site, including, but not limited to, by filing false reports about other Advisors. You will not harass or threaten any other User of the Site.</p>
                 <p class="roboto f-22 text-white mb-3">(j) You will not disclose (which a Customer will be prompted to rate) any information that is classified more aptly as an “Information Request.”</p>
                 <p class="roboto f-22 text-white mb-3">(k) You will abide by all the laws, rules, regulations, and ethical standards pertaining to your profession and/or the profession applicable to categories in which you are an Advisor (including, if applicable, any ethical obligations relating to conflicts of interest).</p>
                 <p class="roboto f-22 text-white mb-3">(l) You agree that any content you provide on the Site and your use of the Site or any additional services (whether such additional services are Informational or Beyond-Information Only, as defined below) initiated through the Site shall not:</p>
                 <ul class="px-5">
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Be fraudulent, inaccurate or misleading; </li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Infringe any third party’s proprietary rights or rights of publicity or privacy</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Be illegal or violate any federal, state, or local law, statute, ordinance, regulation, or ethical code;  </li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Be defamatory, trade libelous, unlawfully threatening or unlawfully harassing;</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Be obscene or contain child pornography;</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Contain any viruses, Trojan horses, or other computer programming routines that may damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or personal information; </li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">Create liability for us or cause us to lose (in whole or in part) the services of our ISPs or other suppliers; or</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">link directly or indirectly to, or include descriptions of, goods or services that are prohibited under the Terms or that you do not have a right to link to or include. If you post material that is adult in nature, such material shall be posted with “Mature Audiences Only” in the listing title and appropriate notices to prevent unauthorized underage viewing and shall be distributed only to people legally permitted to receive such content. You may not consummate any transaction that was initiated using our Service that, by paying us a fee, could cause us to violate any applicable law, statute, ordinance, or regulation. Furthermore, you may not resell or make any commercial use of our system or the content on the Site without Zentia prior written consent. We do not knowingly collect personal information from children under thirteen (13) years of age, and if we become aware that a child under the age of thirteen (13) has submitted personal information to us, we will promptly remove it from our systems. </li>
                 </ul>
                 <h4 class="text-main roboto mb-4 fw-700">7. Duration and Termination of Agreement</h4>
                 <p class="roboto f-22 text-white mb-3">(a) This Agreement shall be for an initial duration of thirty days after Zentia approves the Advisor’s request to use the Site as an Advisor, and will automatically renew for thirty-day intervals on the thirtieth day of the initial duration and of each successive term thereafter (each a "Duration"), unless and until one party gives the other at least ten days' written notice before the end of the then-current Duration of its intention not to renew this Agreement. You may terminate your service and account by written notice via e-mail to info@Zentia.io. Terminations typically will be effective within seven (7) business days after our receipt of your termination notice, at which time your account will be closed, and you will no longer be able to access your former account. Any payments accrued as of the effective date of termination will be payable according to the Terms.</p>
                 <p class="roboto f-22 text-white mb-3">(b) Zentia can terminate this Agreement in the event of a breach of this Agreement by the Advisor, provided that Zentia gives the Advisor notice of the breach of the Agreement (with notice of temporarily suspended access to the Site), with a reasonable opportunity to cure the breach within twenty days, in situations involving, for example, failure to qualify to provide services as an Advisor in the approved subject matter, or Zentia’s good faith belief that the Advisor poses a risk to the safety or health of others; or the Advisor’s engagement in fraud, gaming, or other improper use of the Site or the Services with or through a Customer that has a Membership, which allow Customers who are “Members” to receive the benefits of the Site for multiple questions on the Site for a monthly or other-period recurring fee.</p>
                 <p class="roboto f-22 text-white mb-5">(c) Either party may terminate the Advisor Agreement immediately and without notice upon a material breach.</p>
                 <h4 class="text-main roboto mb-4 fw-700">8. Informational and Educational Purposes Only</h4>
                  <p class="roboto f-22 text-white mb-5">The Zentia Site is a venue for informational and educational purposes only. The formation of a professional-client relationship on the Site is prohibited; however, the formation of a professional-client relationship outside the Site is not prohibited, as long as the User requested those services. Promoting non-free services, provided by the Advisor, outside of the Zentia site is prohibited, except in the case the User requests this information. </p>
                 <h4 class="text-main roboto mb-4 fw-700">9. Content and License</h4>
                 <p class="roboto f-22 text-white mb-3">Any information or communications provided in questions, answers, calls, video calls, messages, requests for information, responses, profiles, Advisor signatures, qualifications, comments, and posts in the Advisor Forum and other places where Users communicate with one another on the Site (“Posts”) will not be considered confidential and may be used by Zentia for any purpose. This may include, but is not limited to, using your signature and/or profile information in emails sent to Customers alerting them to your postings. You understand and agree that Zentia may send Customers emails pertaining to their questions and your answers that are signed by your username (but sent on your behalf from a Zentia email address). For example, Zentia may let the Customer know that you have sent the Customer an email, have responded to their question, and/or have not been paid for an answer (and the Customer should therefore remit payment). As between you and Zentia, Zentia will maintain whatever ownership interest you have in and to the Posts you provide on the Site. Zentia reserves the right to remove any or all of your Posts, in whole or in part, at any time with or without notice.</p>
                 <p class="roboto f-22 text-white mb-3">You grant to Zentia a non-exclusive, irrevocable, perpetual, worldwide, royalty-free, sublicensable (through multiple tiers) right to exercise the copyright, publicity, and database rights, including the right to use, reproduce, display, edit, copy, modify, transmit, publicly perform or create derivative works thereof, that you have in your Posts, in any media now known or not currently known, with respect to any such Posts.</p>
                 <p class="roboto f-22 text-white mb-5">To allow Zentia to assist you in protecting your copyrights in your Answers, at its sole discretion, you grant Zentia the right to act on your behalf solely in submitting DMCA takedown notices to other websites to remove copies of your Answers on Zentia.io from other websites. You agree to notify Zentia at info@Zentia.io within twenty-four (24) hours of posting any portion of your Answers on another website or granting permission to another person or entity to do so, so that Zentia does not submit a DMCA takedown notice for such content. If you do not wish Zentia to assist you in protecting your copyrights in this manner, please send an email to that effect to dmca-agent@Zentia.co . You agree that Zentia has no obligation to make any searches or submit any DMCA takedown notices on your behalf.</p>
                <h4 class="text-main roboto mb-4 fw-700">10. Fees</h4>
                <p class="roboto f-22 text-white mb-2">Customers on Zentia may be presented with a payment model: pay-per-call (“PPC”) model. </p>
                <p class="roboto f-22 text-white mb-3">You acknowledge that Zentia has no control over, and makes no representation or warranty of any kind, as to the ability or willingness of other Users to pay for the answers provided by Advisors. In addition, you acknowledge that you are never required by Zentia to answer any questions on the Site. </p>
                <p class="roboto f-22 text-white mb-3">Once you have more than Twenty U.S. Dollars (US$50) of payments from Customers in your account (you cannot place funds into your account to reach $50; it must be accumulated through Customer payments), you may request payment via the link in your app. Zentia transfers properly requested Customer payments to Advisors via PayPal or Stripe, within 7 business days (or, in its discretion, Zentia may choose to forward Customer payments even without an Advisor’s request for payment). You agree that Zentia has the right to produce discounts, coupons, and/or credits that Users can apply towards reducing the price of a service, affecting the fee that Zentia collects from the Advisor. You agree that Zentia has the right to resolve Customer complaints as it deems necessary or advisable, including, in Zentia’s sole discretion, issuing refunds to Customers to settle disputes. If Zentia decides to issue a refund to a Customer, Zentia may seek reimbursement from the Advisor for such refund, or Zentia may offset any refunds against any future Customer payments to be forwarded to the Advisor. Zentia also reserves the right to resolve accounting discrepancies with Customers in its sole discretion. </p>
                <p class="roboto f-22 text-white mb-2">If Zentia believes, in its sole discretion, that any Customer funds were paid to an Advisor under suspicious circumstances or that funds were derived from a suspicious Customer account, Zentia will investigate the situation until it has reached an adequate resolution, as determined by Zentia in its sole discretion. The investigation or resolution may require the involvement of certain third parties, such as an applicable credit card company. Such an investigation may require Zentia to put a hold on an Advisor’s account. Zentia will make commercially reasonable efforts not to exceed a 90 day hold on an Advisor’s account during such an investigation.</p>
                <p class="roboto f-22 text-white mb-5">Zentia disclaims any warranty that its billing and payment system is without error. If an Advisor believes there is a problem with Zentia’s billing or payment system, the Advisor should notify Zentia by email to info@Zentia.io within thirty (30) days of such problem. Upon receipt of the notification of such a problem, Zentia will, in good faith, work to remedy any alleged payment errors. </p>
                <h4 class="text-main roboto mb-4 fw-700">11. Question Value</h4>
                <p class="roboto f-22 text-white mb-5">You are prohibited from negotiating payment with a User, regarding answers you post to the Site, unless expressly allowed by Zentia.</p>
                <h4 class="text-main roboto mb-4 fw-700">12. Advisor Accounts and Relationship to Zentia</h4>
                <p class="roboto f-22 text-white mb-3">You may not share your account with, nor use the account of, anyone else. You will be solely and fully liable and responsible for all activities and answers provided under your username and account. In addition, if any Zentia account of yours has been suspended or terminated, you may not open another account on the Site.</p>
                <p class="roboto f-22 text-white mb-3">No relationship (such as partnership, agent, joint venturer, or employee) between you and Zentia is created by this Agreement or your participation on the Site. You acknowledge that you are not an employee or agent of Zentia but are, like Customers, only Users of the Site. You shall act in accordance with this status and shall not hold yourself out as an officer, employee or agent of Zentia, nor make any claim based on any right or privilege applicable to Zentia’s employees. Under no circumstances shall you look to Zentia as your employer, or as a partner, agent, or principal. Nothing regarding your participation on the Site will be considered as an endorsement, referral or recommendation by Zentia of you or the answers you provide and you will not, either on the Site or in any other forum or by any other means, suggest such an endorsement.</p>
                <p class="roboto f-22 text-white mb-5">It is the express intention of Zentia and the Advisor that the Advisor be an independent contractor. Nothing in this Agreement shall in any way be construed to constitute the Advisor as an agent, employee, or representative of Zentia. Without limiting the generality of the foregoing, the Advisor is not authorized to bind Zentia to any liability or obligation or to represent that the Advisor has any such authority. Advisor agrees to furnish all tools and materials necessary to answer questions on the Site and shall incur all expenses associated with such performance. Advisor further agrees that any use of site tools, Zentia’s mobile application or any other tools (“Tools”) offered by Zentia is optional and such Tools are purely offered for Advisor’s convenience and usage of such Tools are not mandatory. Advisor acknowledges and agrees that Advisor is obligated to report as income all compensation received by Zentia pursuant to this Agreement. Advisor agrees to and acknowledges the obligation to pay all self-employment and other taxes on such income. Advisor will receive no Zentia-sponsored benefits such as, but not limited to, paid vacation, sick leave, medical insurance, and 401k participation. If Advisor is reclassified by a state or federal agency, court, or arbitrator as Zentia’s employee, Advisor will become a reclassified employee and will receive no benefits from Zentia, except those mandated by state or federal law, even if by the terms of Zentia’s benefit plans or programs of the Company in effect at the time of such reclassification, Advisor would otherwise be eligible for such benefits.</p>
                <h4 class="text-main roboto mb-4 fw-700">13. Limited Exclusivity and Other Agreements</h4>
                <p class="roboto f-22 text-white mb-3">By agreeing to this Advisor Agreement and completing the online registration process, you are agreeing that:</p>
                <p class="roboto f-22 text-white mb-3">(a) You will not post – or authorize anyone else to post – any portion of your calls or answers on Zentia or any other fee-based question-and-answer website, unless that question-and-answer component is via the Zentia referral program or it is a website on which you are the only person answering questions. This does not prohibit you from providing the same substantive answer to a question, but only from providing it using the same words as used on the Site.</p>
                <p class="roboto f-22 text-white mb-3">(b) The provisions of this Agreement are not intended to prevent you from practicing your profession, but only from engaging in the limited activity described therein.</p>
                <p class="roboto f-22 text-white mb-5">(c) You will not make any statement that disparages Zentia, its services, products, directors, officers, employees, shareholders or agents, except as required by law or in communications exclusively to Zentia.</p>
                <h4 class="text-main roboto mb-4 fw-700">14. Confidentiality</h4>
                <p class="roboto f-22 text-white mb-3">You acknowledge that Zentia and its licensors and suppliers own the rights to the Zentia website and the content displayed on the Site other than Posts. You shall not modify, reverse engineer, decompile, disassemble, or attempt to derive the source code of the Zentia website, any software distributed by or assist any other person or entity in doing so. You acknowledge that all content, including, but not limited to, text, software, music, sound, photographs, video, graphics or other material contained in listings, sponsor advertisements or email-distributed, commercially produced information presented to you by the Service, by Zentia, Users, or Zentia advertisers or other content providers, is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. You may not modify, copy, reproduce, republish, upload, post, transmit, or distribute in any way content available through the Service, whether done directly or through intermediaries (including, but not limited to, by means of spiders, robots, crawlers, scrapers, framing, iframes or RSS feeds),  including, but not limited to, code and software for commercial purposes. For permission to use third-party materials appearing on the Site, please contact the copyright owner. You do not acquire ownership rights to any content, document or other materials viewed through the Site. The posting of information or materials on the Site does not constitute a waiver of any right in such information and materials.</p>
                <p class="roboto f-22 text-white mb-3">Any access to or use of Zentia to design, develop, test, update, operate, modify, maintain, support, market, advertise, distribute or otherwise make available any program, application or service (including, without limitation, any device, technology, product, computer program, mobile device application, website, or mechanical or personal service) that enables or provides access to, use of, operation of or interoperation with Zentia (including, without limitation, to access content, post content, cross-post content, re-post content, respond or reply to content, verify content, transmit content, create accounts, verify accounts, use accounts, circumvent and/or automate technological security measures or restrictions, or flag content) without the prior written authorization of Zentia is prohibited. This prohibition specifically applies to, but is not limited to, software, programs, applications, and services for use or operation on or by any computer and/or any electronic, wireless and/or mobile device, technology, or product that exists now or in the future.</p>
                <p class="roboto f-22 text-white mb-3">If you access Zentia or copy, display, distribute, perform, or create derivative works from content displayed on the Site or other intellectual property in violation of this Agreement, your access, copying, display, distribution, performance, or derivative work is unauthorized. Circumvention of any technological restriction or security measure on Zentia or any provision of this Agreement that restricts content, conduct, accounts or access is expressly prohibited. For purposes of this paragraph, you agree that cached copies of Zentia webpages on your computer or computer server constitute “copies” under the Copyright Act, 17 U.S.C. § 101.</p>
                <p class="roboto f-22 text-white mb-3">You agree that Posts on the Site, materials, ideas, comments, and testimonials that you submit on the Site or other venues, including, but not limited to, the Zentia blogs and the Zentia venues on <span class="text-main"> www.facebook.com</span>, <span class="text-main">www.instagram.com</span>, <span class="text-main">www.twitter.com</span>, <span class="text-main"> www.linkedin.com</span>, <span class="text-main">www.youtube.com</span> , <span class="text-main"> www.pinterest.com</span>, <span class="text-main"> plus.google.com</span> , <span class="text-main"> www.flickr.com</span> , or to the Site administrator or any employee, officer or agent of Zentia (“User Content”), will not be considered confidential and may be used by Zentia, in its sole discretion, without any obligation to compensate you for the use of or to return any submitted materials. You also agree that Zentia owns, and has the right to register in its name, trademarks and service marks for any category names that you create on Zentia, so do not use a category name that you want to reserve for your own benefit. Zentia may use other trademarks or service marks in lieu of the category names that you create.</p>
                <p class="roboto f-22 text-white mb-3">You grant to Zentia a non-exclusive, irrevocable, perpetual, worldwide, royalty-free, sublicensable (through multiple tiers) right to exercise the copyright, publicity, and database rights, including the right to use, reproduce, display, edit, copy, modify, transmit, publicly perform, extract and create derivative works thereof, that you have in your Posts, recorded calls, and User Content, in any media now known or not currently known, with respect to any such Posts and other User Content. </p>
                <p class="roboto f-22 text-white mb-5">Notwithstanding the above, please note that Advisors are granted access to the Site beyond the access granted to other Users and, as such, have access to information not known by non-Advisor Users of the Site (“Confidential Information”). Advisors shall maintain all Confidential Information in confidence; shall use such Confidential Information in confidence; shall use such Confidential Information only in connection with their legitimate activities on the Site; shall not use Confidential Information for the purpose of developing, operating, or participating in any competing service; and shall not disclose Confidential Information to non-Advisors unless required by law.</p>
                <h4 class="text-main roboto mb-4 fw-700">15. No Endorsement of Non-Zentia Entity; No Relationship with Users</h4>
                <p class="roboto f-22 text-white mb-5">Zentia may endeavor to offer to its Users products and services offered by non-Zentia entities. The Site may contain links to third party websites and service providers (collectively, “Third Party Services”) that are not owned or controlled by Zentia. Zentia has no control over and assumes no responsibility for the content, practices, and privacy policies of such Third Party Services. Zentia encourages you to, and you acknowledge that you are solely responsible for, reviewing and complying with any third party terms and conditions and privacy policies. Zentia cannot and will not censor or edit the content of any Third Party Service. Placement of information, logos, links, or names of such non-Zentia entities on the Site does not constitute an endorsement or warranty of these entities, their products or services. By using this Site, you agree that Zentia is not responsible for, and you take full responsibility for, a decision to visit or patronize any such Third Party Service or entity, you hold Zentia harmless from any and all liability arising from such actions, and you expressly relieve Zentia from all liability arising from your use of Third Party Services. IT IS THE RESPONSIBILITY OF THE USER TO EVALUATE THE ACCURACY, COMPLETENESS, AND USEFULNESS OF ANY OPINION, ANSWER OR OTHER CONTENT AVAILABLE THROUGH THE SITE FROM THIRD PARTIES OR OBTAINED FROM A LINKED SITE. PLEASE SEEK THE ADVICE OF PROFESSIONALS, AS APPROPRIATE, REGARDING THE EVALUATION OF ANY SPECIFIC OPINION, ANSWER, PRODUCT, SERVICE, OR OTHER CONTENT.</p>
                <h4 class="text-main roboto mb-4 fw-700">16. Information Control and Storage</h4>
                <p class="roboto f-22 text-white mb-3">We do not control the information provided by Users, which you may find to be offensive, harmful, inaccurate, or deceptive. Please use caution and common sense when using the Site. There are also risks of dealing with underage persons or people acting under false pretenses. Additionally, there may be risks dealing with international trade and foreign nationals. By using this Site, you agree to accept such risks and that Zentia is not responsible for the acts or omissions of Users on the Site.</p>
                <p class="roboto f-22 text-white mb-5">The amount of storage space per User is currently limited. You agree that Zentia is not responsible or liable for the deletion or failure to store content and/or other information. </p>
                <h4 class="text-main roboto mb-4 fw-700">17. Exclusion of Warranties</h4>
                <p class="roboto f-22 text-white mb-3">Zentia SERVICES, SOFTWARES, AND RELATED DOCUMENTATION ARE PROVIDED “AS IS” AND WITHOUT ANY WARRANTY OF ANY KIND EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. NO INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM US THROUGH THIS SITE SHALL CREATE ANY WARRANTY, REPRESENTATION OR GUARANTEE NOT EXPRESSLY STATED IN THESE TERMS. </p>
                <p class="roboto f-22 text-white mb-3">Zentia DOES NOT REPRESENT OR WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THIS SITE OR THE SERVER THAT MAKES IT AVAILABLE, ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. Zentia DOES NOT WARRANT OR REPRESENT THAT THE USE OR THE RESULTS OF THE USE OF THE MATERIALS AVAILABLE THROUGH THE SERVICE, FROM THIRD PARTIES OR A LINKED SITE WILL BE CORRECT, ACCURATE, TIMELY, RELIABLE OR OTHERWISE. SOME STATES OR OTHER JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. YOU MAY ALSO HAVE OTHER RIGHTS THAT VARY FROM STATE TO STATE AND JURISDICTION TO JURISDICTION.</p>
                <p class="roboto f-22 text-white mb-3">UNDER NO CIRCUMSTANCES WILL Zentia BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A USER’S RELIANCE ON INFORMATION OBTAINED THROUGH THE SITE, FROM THIRD PARTIES (SUCH AS AdvisorS OR OTHERS) OR A LINKED SITE, OR USER’S RELIANCE ON ANY PRODUCT OR SERVICE OBTAINED FROM A THIRD PARTY OR A LINKED SITE. USE OF THIS SITE IS AT USERS’ SOLE RISK.</p>
                <p class="roboto f-22 text-white mb-5">NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM Zentia OR THROUGH OR FROM THE Zentia SERVICES SHALL CREATE ANY WARRANTY.</p>
                 <h4 class="text-main roboto mb-4 fw-700">18. Right to Discontinue</h4>
                 <p class="roboto f-22 text-white mb-3">At any time, with or without notice, for any or no reason, and in its sole discretion, Zentia reserves the right to modify or discontinue any portion or all of the Site or the Services. Advisor has no rights in and to the Site and Services.</p>
                 <p class="roboto f-22 text-white mb-5">You are never required to answer any questions posted on the website or asked on a call. </p>
                 <h4 class="text-main roboto mb-4 fw-700">19. Press Releases and Third-Party Press about Zentia</h4>
                 <p class="roboto f-22 text-white mb-5">The Site may contain press releases and other information about Zentia. While this information was believed to be accurate as of the date prepared, we disclaim any duty or obligation to update this information or any press releases. Information about companies other than ours contained in the press release or otherwise, should not be relied upon as being provided or endorsed by Zentia. Likewise, third-party press about Zentia or the Site should not be relied upon as being provided or endorsed by Zentia.</p>
                 <h4 class="text-main roboto mb-4 fw-700">20. Indemnification</h4>
                 <p class="roboto f-22 text-white mb-5">You agree to indemnify and hold Zentia, any and all parent, subsidiary and affiliate organizations, officers, directors, agents, shareholders, consultants, employees, successors, and assigns harmless from and against all losses, costs, liabilities and expenses, including reasonable attorneys’ fees, asserted by any third party that are in any way due to, or arising out of, your use of or conduct on the Site, including, without limitation, that results from any answer provided or relied upon on the Site.</p>
                 <h4 class="text-main roboto mb-4 fw-700">21. Dispute Resolution</h4>
                 <p class="roboto f-22 text-white mb-3">This Section 21 may be referred to as the parties’ “Dispute Resolution Agreement.” If you have a dispute with Zentia or if Zentia has a dispute with you and such dispute cannot be resolved informally, such dispute will be resolved on an individual basis in accordance with the provisions set forth below: <br> (a) Informal Resolution.  Prior to initiating mediation or arbitration, the party with a grievance must:</p>
                 <p class="roboto f-22 text-white mb-3">(1) Notify the other party, in writing, of the facts of the dispute and all damages claimed. Such a writing must be sent to (a) the Advisor’s email address on file with info@Zentia.io</p>
                 <p class="roboto f-22 text-white mb-3">(2) The party receiving the Dispute Notification has thirty (30) days from receipt of the Dispute Notification to respond.</p>
                 <p class="roboto f-22 text-white mb-5">(3) The other party then has 15 days to reply to the response.</p>
                 <p class="roboto f-22 text-white mb-4">(a) Arbitration.</p>
                 <ul class="px-5">
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">(i) Mutual agreement to arbitrate. If mediation does not occur or if mediation does not resolve the dispute, then both parties agree that all disputes between them, including without limitation, those disputes arising out of or related to this Agreement, the Services provided under this Agreement, the termination of this Agreement, the use of the Site, and the “Terms” as defined in the Agreement, shall be determined exclusively by final and binding arbitration before a single, neutral arbitrator as described herein.</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">(ii) Covered claims. Claims subject to arbitration under this Dispute Resolution Agreement include, but are not limited to, the following types of claims between and among Advisor on the one hand, and Zentia, its subsidiaries, affiliates, shareholders, officers, directors, employees, benefit plans, or agents, any alleged joint employers, and any of Zentia’s Users (including Customers and Advisors), on the other hand: breach of contract; discrimination, harassment, or retaliation; wrongful discharge; negligence or other tort claims including defamation, libel, slander, fraud, invasion of privacy, and infliction of emotional distress; claims for wages, overtime, benefits, or other compensation; and all other statutory, regulatory, contractual, or tort claims or claims of violation of any international, federal/national, state/provincial, or local statute, ordinance, governmental enactment, common law duty, provision, or doctrine. Except as provided below, the parties voluntarily waive all rights to trial in court before a judge or jury on claims between them. Judgment upon the arbitrator's award may be entered in any court of competent jurisdiction. The only disputes and actions excluded from this Dispute Resolution Agreement are: <br> (a) actions to enforce this Dispute Resolution Agreement, compel arbitration, or claims by either party seeking temporary injunctive relief prior to the appointment of the arbitrator; and <br> (b) claims for which this Dispute Resolution Agreement would be invalid as a matter of law. Individual knowingly and voluntarily waives the right to file or seek relief in a court seeking recovery of money damages.</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">(iii) Arbitration rules and selection of arbitrator. Unless the parties agree otherwise in writing, the AAA shall administer the resolution of covered disputes pursuant to the Commercial Arbitration Rules and the supplementary procedures for Consumer Related Disputes (collectively, "AAA rules"). Copies of these rules can be obtained at the AAA’s website (www.adr.org) or by calling the AAA at 1-800-778-7879. Federal Rule of Civil Procedure 68 (“Offer of Judgment”) shall apply, as well. In the event of any inconsistency between this Dispute Resolution Agreement and the applicable rules of the AAA, this Dispute Resolution Agreement shall govern. The parties shall have 30 days from receipt of a notice of arbitration to select a mutually agreeable arbitrator. If the parties are unable to jointly select the arbitrator, the arbitrator shall be selected as provided in the AAA’s rules.</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">1. If the Advisor initiates arbitration under this Dispute Resolution Agreement and is otherwise required to pay a filing fee under the relevant AAA rules, Zentia agrees that, unless the claim is for $5,000 or more, the Advisor’s share of the filing fee is limited to $50, and after the Advisor submits proof of payment of the filing fee to Zentia, Zentia will promptly reimburse the Advisor for all but $50 of the filing fee. If, however, the arbitrator finds that either the substance of the Advisor’s claim or the relief sought in the claim is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all such fees will be governed by the AAA rules. </li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">2. If Zentia initiates arbitration under this Dispute Resolution Agreement, Zentia will pay all costs unique to arbitration (as compared to the costs of adjudicating the same claims before a court or agency), including the regular and customary administrative fees and expenses charged by AAA. Any dispute as to whether a cost is unique to arbitration shall be resolved by the arbitrator.</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">3. Except as provided for in Federal Rule of Civil Procedure 68, each party shall pay its own attorneys’ fees and any costs that are not unique to the arbitration (i.e., costs that each party would incur if the claim(s) were litigated in a court or agency such as costs to subpoena witnesses and/or documents; take depositions and purchase deposition transcripts; copy documents; etc.).</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">(vi) Authority of the arbitrator. The arbitrator shall have the same authority to order remedies to individual claimants as would a court of competent jurisdiction. The arbitrator shall also have the same authority to decide dispositive motions as would a court, though he or she may establish appropriate and less formal procedures for such motions consistent with the expedited nature of arbitration proceedings. The arbitrator shall have the authority to issue subpoenas to compel the attendance of witnesses at the arbitration hearing and to compel the production of documents during discovery. Except as provided below, the arbitrator shall have the authority to resolve any dispute relating to the interpretation, applicability, enforceability, or formation of this Dispute Resolution Agreement, including without limitation any claim that the Dispute Resolution Agreement is void or voidable. The arbitrator shall not have the authority to hear disputes not recognized by existing law and shall dismiss such claims upon motion by either party in accordance with the standards and burdens generally applicable in federal district court.</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">(vii) Waiver of class, collective, and/or representative actions. Advisor understands and agrees that all claims covered by this Dispute Resolution Agreement that Advisor may have against Zentia must be brought in Advisor’s individual capacity and not as a plaintiff or class member in any purported class action, collective action or representative action proceeding. Similarly, any claims covered by this Dispute Resolution Agreement that Zentia may have against Advisor may not be brought as a plaintiff or class member in any purported class action, collective action or representative action proceeding. Advisor understands that there is no right or authority for any dispute covered by this Dispute Resolution Agreement to be heard or arbitrated on a collective action basis, class action basis, as a private attorney general, or on bases involving claims or disputes brought in a representative capacity on behalf of the general public, on behalf of other Zentia company employees (or any of them) or on behalf of other persons alleged to be similarly situated. Advisor understands that there are no bench or jury trials and no class actions or representative actions permitted under this Dispute Resolution Agreement. The arbitrator shall not consolidate claims of different Advisors into one proceeding, nor shall the arbitrator have the power to hear arbitration as a class action, collective action, or representative action. Any disputes regarding the enforceability or scope of this provision including, but not limited to, whether class, collective, or representative actions are authorized in arbitration by this Dispute Resolution Agreement, shall be decided by a court of competent jurisdiction rather than by an arbitrator.</li>
                    <li class="mb-3 text-white roboto f-22" style="list-style: circle;">(viii) Form of the award. The arbitrator shall render a written award setting forth his or her findings of fact and conclusions of law.</li>
                 </ul>
                 <h4 class="text-main roboto mb-4 fw-700">22. Choice of Law</h4>
                 <p class="roboto f-22 text-white mb-5">The Terms shall be governed by, and construed in accordance with the laws of the State of Delaware, without regard to its conflicts of law provisions, except as set forth in Section 21 of this Agreement (the “Dispute Resolution Agreement”).</p>
                <h4 class="text-main roboto mb-4 fw-700">23. Miscellaneous</h4>
                <p class="roboto f-22 text-white mb-3">Failure to enforce any provision of this Agreement by Zentia shall not constitute a waiver of any provision by Zentia. If any provision of this Agreement is deemed invalid or unenforceable, such provision shall be ineffective only to the extent of such prohibition or invalidity without invalidating the remainder of such provision or the remaining provisions of the Agreement. All provisions not affected by the invalidity shall remain in full force and effect.</p>
                 <p class="roboto f-22 text-white mb-3">The Terms constitute the complete and exclusive statement of the Agreement between you and us. It supersedes any and all prior or contemporaneous agreement, oral or written, and any other communications, representations, warranties and understanding relating to the subject matter of the Terms. If there is a conflict between an oral or written representation of any Zentia employee or agent and the Terms (other than modifications to the Terms executed in writing by the CEO or authorized-in-fact representative of Zentia), the Terms will prevail. To the extent the Terms are in conflict or inconsistent with one another, this Agreement and the Privacy Policy will prevail for Advisors over other terms, rules, policies, and FAQs on the Site. If any provision(s) of the Terms is held by a court or arbitrator of competent jurisdiction to be contrary to law, then such provision(s) shall be construed, as nearly as possible, to reflect the intentions of the parties and the other provisions shall remain in full force and effect. Zentia’s failure to exercise or enforce any of the Terms shall not constitute a waiver of Zentia’s right to exercise or enforce the Terms as to the same or another instance.</p>
                 <p class="roboto f-22 text-white mb-3">Headings in this and Related Agreements are for purposes of reference only and shall not limit or otherwise affect the meaning of the Terms.</p>
                 <p class="roboto f-22 text-white mb-3">You agree that Zentia may assign the Terms to any other entity of its choosing, with or without notice to you. You may not assign the Terms to any other party for any reason. Zentia shall not be deemed to have waived any of its rights or remedies unless such waiver is in writing and signed by an authorized officer of Zentia. No delay or omission on the part of Zentia in exercising any rights or remedies shall operate as a waiver of such rights or remedies or any other rights or remedies on future occasions.</p>
                 <p class="roboto f-22 text-white mb-3">Certain sections of this Agreement, by their terms, survive the termination of this Agreement.</p>
            </div>
        </div>
    </section>
    
@endsection
@section('scripts')  
@endsection